version: "3"
services:
  my-rabbit:
    image: 'rabbitmq:3-management'
    hostname: "my-rabbit"
    env_file: 
      - ./rabbitmq/.env
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    labels:
      type: "db"
      name: "my-rabbit"
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - rabbit-data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
  
  my-mysql:
    image: 'mysql:5.7'
    hostname: "my-mysql"
    env_file:
      - ./mysql/.env
    ports:
      - 3306:3306
    restart: always
    labels:
      type: "db"
      name: "my-mysql"
    volumes:
      - ./mysql/example.sql:/docker-entrypoint-initdb.d/example.sql
      - mysql-data:/var/lib/mysql
  
  my-postgres:
    image: 'postgres:9.4'
    hostname: 'my-postgres'
    env_file:
      - ./postgres/.env
    ports:
      - 5432:5432
    restart: always
    labels:
      type: 'db'
      name: 'my-postgres'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  my-mongo:
    image: 'mongo:latest'
    hostname: "my-mongo"
    env_file:
      - ./mongo/.env
    restart: always
    ports:
      - 27017:27017
    labels:
      type: "db"
      name: "my-mongo"
    volumes:
      - ./mongo/example.js:/docker-entrypoint-initdb.d/example.js
      - mongo-data:/data/db
  
  my-redis:
    image: 'redis:latest'
    hostname: "my-redis"
    restart: always
    ports:
      - 6379:6379
    labels:
      type: "db"
      name: "my-redis"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  
  my-portainer:
    image: 'portainer/portainer'
    hostname: 'my-portainer'
    restart: always
    ports:
      - 9000:9000
    labels:
      type: "db"
      name: "my-portainer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: -H unix:///var/run/docker.sock

volumes:
  rabbit-data:
  mysql-data:
  postgres-data:
  mongo-data:
  redis-data:
  portainer_data: