version: '3'

services:

  kong-database:
    image: postgres:9.6
    hostname: 'my-postgres'
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    restart: always
    ports:
      - 15432:5432
    labels:
      type: 'kong'
      name: 'kong-database'
    volumes:
      - kong-database-data:/var/lib/postgresql/data

  kong-migration:
    image: kong:latest
    container_name: kong-migration
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    labels:
      type: 'kong'
      name: 'kong-migration'
    command: sh -c "kong migrations up && touch migrations_run && sleep 30"

  kong:
    image: kong:latest
    container_name: kong
    depends_on:
      - kong-migration
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    labels:
      type: 'kong'
      name: 'kong'
    ports:
      - 8001:8001
      - 8000:8000

  kong-dashboard:
    image: pgbi/kong-dashboard
    container_name: kong-dashboard
    ports:
      - 8081:8080
    labels:
      type: 'kong'
      name: 'kong-dashboard'
    depends_on:
      - kong
    command: start --kong-url http://kong:8001 --basic-auth root1=password1

volumes:
  kong-database-data: